// Get Cart by User Login
export const GET_CART_BY_USER_LOGIN_REQUEST = "GET_CART_BY_USER_LOGIN_REQUEST";
export const GET_CART_BY_USER_LOGIN_SUCCESS = "GET_CART_BY_USER_LOGIN_SUCCESS";
export const GET_CART_BY_USER_LOGIN_FAILURE = "GET_CART_BY_USER_LOGIN_FAILURE";

// Delete Cart
export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";

// Get All Cart Items
export const GET_ALL_CART_ITEM_REQUEST = "GET_ALL_CART_ITEM_REQUEST";
export const GET_ALL_CART_ITEM_SUCCESS = "GET_ALL_CART_ITEM_SUCCESS";
export const GET_ALL_CART_ITEM_FAILURE = "GET_ALL_CART_ITEM_FAILURE";

// Add Cart Item to Cart
export const ADD_CART_ITEM_TO_CART_REQUEST = "ADD_CART_ITEM_TO_CART_REQUEST";
export const ADD_CART_ITEM_TO_CART_SUCCESS = "ADD_CART_ITEM_TO_CART_SUCCESS";
export const ADD_CART_ITEM_TO_CART_FAILURE = "ADD_CART_ITEM_TO_CART_FAILURE";

// Update Quantity of Cart Item
export const UPDATE_QUANTITY_OF_CART_ITEM_REQUEST = "UPDATE_QUANTITY_OF_CART_ITEM_REQUEST";
export const UPDATE_QUANTITY_OF_CART_ITEM_SUCCESS = "UPDATE_QUANTITY_OF_CART_ITEM_SUCCESS";
export const UPDATE_QUANTITY_OF_CART_ITEM_FAILURE = "UPDATE_QUANTITY_OF_CART_ITEM_FAILURE";

// Delete Cart Item
export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_FAILURE = "DELETE_CART_ITEM_FAILURE";

// place order
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";

//get order by id
export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";
// get order by user login
export const GET_ORDER_BY_USER_LOGIN_REQUEST = "GET_ORDER_BY_USER_LOGIN_REQUEST";
export const GET_ORDER_BY_USER_LOGIN_SUCCESS = "GET_ORDER_BY_USER_LOGIN_SUCCESS";
export const GET_ORDER_BY_USER_LOGIN_FAILURE = "GET_ORDER_BY_USER_LOGIN_FAILURE";


