export const GET_MY_RESTAURANT_REQUEST = "GET_MY_RESTAURANT_REQUEST";
export const GET_MY_RESTAURANT_SUCCESS = "GET_MY_RESTAURANT_SUCCESS";
export const GET_MY_RESTAURANT_FAILURE = "GET_MY_RESTAURANT_FAILURE";

export const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAILURE = "CREATE_RESTAURANT_FAILURE";

export const GET_ALL_RESTAURANT_REQUEST = "GET_ALL_RESTAURANT_REQUEST";
export const GET_ALL_RESTAURANT_SUCCESS = "GET_ALL_RESTAURANT_SUCCESS";
export const GET_ALL_RESTAURANT_FAILURE = "GET_ALL_RESTAURANT_FAILURE";

// Delete Restaurant
export const DELETE_RESTAURANT_REQUEST = "DELETE_RESTAURANT_REQUEST";
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_FAILURE = "DELETE_RESTAURANT_FAILURE";

// Update Restaurant
export const UPDATE_RESTAURANT_REQUEST = "UPDATE_RESTAURANT_REQUEST";
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
export const UPDATE_RESTAURANT_FAILURE = "UPDATE_RESTAURANT_FAILURE";


// Update Restaurant Status
export const UPDATE_RESTAURANT_STATUS_REQUEST =
  "UPDATE_RESTAURANT_STATUS_REQUEST";
export const UPDATE_RESTAURANT_STATUS_SUCCESS =
  "UPDATE_RESTAURANT_STATUS_SUCCESS";
export const UPDATE_RESTAURANT_STATUS_FAILURE =
  "UPDATE_RESTAURANT_STATUS_FAILURE";

// Create Category
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

// Get Category of Restaurant
export const GET_CATEGORY_OF_RESTAURANT_REQUEST =
  "GET_CATEGORY_OF_RESTAURANT_REQUEST";
export const GET_CATEGORY_OF_RESTAURANT_SUCCESS =
  "GET_CATEGORY_OF_RESTAURANT_SUCCESS";
export const GET_CATEGORY_OF_RESTAURANT_FAILURE =
  "GET_CATEGORY_OF_RESTAURANT_FAILURE";
// Update Category
export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

// Delete Category
export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

//CUSTOMER
export const GET_CATEGORY_OF_RESTAURANT_ID_FAILURE =
  "GET_CATEGORY_OF_RESTAURANT_ID_FAILURE";
export const GET_CATEGORY_OF_RESTAURANT_ID_REQUEST =
  "GET_CATEGORY_OF_RESTAURANT_ID_REQUEST";
export const GET_CATEGORY_OF_RESTAURANT_ID_SUCCESS =
  "GET_CATEGORY_OF_RESTAURANT_ID_SUCCESS";

  // Get Restaurant by ID
export const GET_RESTAURANT_BY_ID_REQUEST = "GET_RESTAURANT_BY_ID_REQUEST";
export const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS";
export const GET_RESTAURANT_BY_ID_FAILURE = "GET_RESTAURANT_BY_ID_FAILURE";


// Add Favourite Restaurant
export const ADD_FAVOURITE_RESTAURANT_REQUEST = "ADD_FAVOURITE_RESTAURANT_REQUEST";
export const ADD_FAVOURITE_RESTAURANT_SUCCESS = "ADD_FAVOURITE_RESTAURANT_SUCCESS";
export const ADD_FAVOURITE_RESTAURANT_FAILURE = "ADD_FAVOURITE_RESTAURANT_FAILURE";

// Get Favourite Restaurants
export const GET_FAVOURITE_RESTAURANTS_REQUEST = "GET_FAVOURITE_RESTAURANTS_REQUEST";
export const GET_FAVOURITE_RESTAURANTS_SUCCESS = "GET_FAVOURITE_RESTAURANTS_SUCCESS";
export const GET_FAVOURITE_RESTAURANTS_FAILURE = "GET_FAVOURITE_RESTAURANTS_FAILURE";

// Search Restaurants
export const SEARCH_RESTAURANTS_REQUEST = "SEARCH_RESTAURANTS_REQUEST";
export const SEARCH_RESTAURANTS_SUCCESS = "SEARCH_RESTAURANTS_SUCCESS";
export const SEARCH_RESTAURANTS_FAILURE = "SEARCH_RESTAURANTS_FAILURE";

// food 



// Create Food
export const CREATE_FOOD_REQUEST = "CREATE_FOOD_REQUEST";
export const CREATE_FOOD_SUCCESS = "CREATE_FOOD_SUCCESS";
export const CREATE_FOOD_FAILURE = "CREATE_FOOD_FAILURE";

// Update Food
export const UPDATE_FOOD_REQUEST = "UPDATE_FOOD_REQUEST";
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS";
export const UPDATE_FOOD_FAILURE = "UPDATE_FOOD_FAILURE";

// Delete Food
export const DELETE_FOOD_REQUEST = "DELETE_FOOD_REQUEST";
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
export const DELETE_FOOD_FAILURE = "DELETE_FOOD_FAILURE";

// Get Food by Restaurant
export const GET_FOOD_BY_RESTAURANT_REQUEST = "GET_FOOD_BY_RESTAURANT_REQUEST";
export const GET_FOOD_BY_RESTAURANT_SUCCESS = "GET_FOOD_BY_RESTAURANT_SUCCESS";
export const GET_FOOD_BY_RESTAURANT_FAILURE = "GET_FOOD_BY_RESTAURANT_FAILURE";
//get food by restaurantId
export const GET_FOOD_BY_RESTAURANT_ID_REQUEST = "GET_FOOD_BY_RESTAURANT_ID_REQUEST";
export const GET_FOOD_BY_RESTAURANT_ID_SUCCESS = "GET_FOOD_BY_RESTAURANT_ID_SUCCESS";
export const GET_FOOD_BY_RESTAURANT_ID_FAILURE = "GET_FOOD_BY_RESTAURANT_ID_FAILURE";
// Update Availability
export const UPDATE_AVAILABILITY_REQUEST = "UPDATE_AVAILABILITY_REQUEST";
export const UPDATE_AVAILABILITY_SUCCESS = "UPDATE_AVAILABILITY_SUCCESS";
export const UPDATE_AVAILABILITY_FAILURE = "UPDATE_AVAILABILITY_FAILURE";

// Get All Foods
export const GET_ALL_FOODS_REQUEST = "GET_ALL_FOODS_REQUEST";
export const GET_ALL_FOODS_SUCCESS = "GET_ALL_FOODS_SUCCESS";
export const GET_ALL_FOODS_FAILURE = "GET_ALL_FOODS_FAILURE";

// Get Food by ID
export const GET_FOOD_BY_ID_REQUEST = "GET_FOOD_BY_ID_REQUEST";
export const GET_FOOD_BY_ID_SUCCESS = "GET_FOOD_BY_ID_SUCCESS";
export const GET_FOOD_BY_ID_FAILURE = "GET_FOOD_BY_ID_FAILURE";


// Create Ingredient
export const CREATE_INGREDIENT_REQUEST = "CREATE_INGREDIENT_REQUEST";
export const CREATE_INGREDIENT_SUCCESS = "CREATE_INGREDIENT_SUCCESS";
export const CREATE_INGREDIENT_FAILURE = "CREATE_INGREDIENT_FAILURE";

// Update Ingredient
export const UPDATE_INGREDIENT_REQUEST = "UPDATE_INGREDIENT_REQUEST";
export const UPDATE_INGREDIENT_SUCCESS = "UPDATE_INGREDIENT_SUCCESS";
export const UPDATE_INGREDIENT_FAILURE = "UPDATE_INGREDIENT_FAILURE";

// Get Ingredients by Restaurant
export const GET_INGREDIENTS_BY_RESTAURANT_REQUEST = "GET_INGREDIENTS_BY_RESTAURANT_REQUEST";
export const GET_INGREDIENTS_BY_RESTAURANT_SUCCESS = "GET_INGREDIENTS_BY_RESTAURANT_SUCCESS";
export const GET_INGREDIENTS_BY_RESTAURANT_FAILURE = "GET_INGREDIENTS_BY_RESTAURANT_FAILURE";

// Delete Ingredient
export const DELETE_INGREDIENT_REQUEST = "DELETE_INGREDIENT_REQUEST";
export const DELETE_INGREDIENT_SUCCESS = "DELETE_INGREDIENT_SUCCESS";
export const DELETE_INGREDIENT_FAILURE = "DELETE_INGREDIENT_FAILURE";