// Create Food
export const CREATE_FOOD_REQUEST = "CREATE_FOOD_REQUEST";
export const CREATE_FOOD_SUCCESS = "CREATE_FOOD_SUCCESS";
export const CREATE_FOOD_FAILURE = "CREATE_FOOD_FAILURE";

// Update Food
export const UPDATE_FOOD_REQUEST = "UPDATE_FOOD_REQUEST";
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS";
export const UPDATE_FOOD_FAILURE = "UPDATE_FOOD_FAILURE";

// Delete Food
export const DELETE_FOOD_REQUEST = "DELETE_FOOD_REQUEST";
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
export const DELETE_FOOD_FAILURE = "DELETE_FOOD_FAILURE";

// Get Food by Restaurant
export const GET_FOOD_BY_RESTAURANT_REQUEST = "GET_FOOD_BY_RESTAURANT_REQUEST";
export const GET_FOOD_BY_RESTAURANT_SUCCESS = "GET_FOOD_BY_RESTAURANT_SUCCESS";
export const GET_FOOD_BY_RESTAURANT_FAILURE = "GET_FOOD_BY_RESTAURANT_FAILURE";
//get food by restaurantId
export const GET_FOOD_BY_RESTAURANT_ID_REQUEST = "GET_FOOD_BY_RESTAURANT_ID_REQUEST";
export const GET_FOOD_BY_RESTAURANT_ID_SUCCESS = "GET_FOOD_BY_RESTAURANT_ID_SUCCESS";
export const GET_FOOD_BY_RESTAURANT_ID_FAILURE = "GET_FOOD_BY_RESTAURANT_ID_FAILURE";
// Update Availability
export const UPDATE_AVAILABILITY_REQUEST = "UPDATE_AVAILABILITY_REQUEST";
export const UPDATE_AVAILABILITY_SUCCESS = "UPDATE_AVAILABILITY_SUCCESS";
export const UPDATE_AVAILABILITY_FAILURE = "UPDATE_AVAILABILITY_FAILURE";

// Get All Foods
export const GET_ALL_FOODS_REQUEST = "GET_ALL_FOODS_REQUEST";
export const GET_ALL_FOODS_SUCCESS = "GET_ALL_FOODS_SUCCESS";
export const GET_ALL_FOODS_FAILURE = "GET_ALL_FOODS_FAILURE";

// Get Food by ID
export const GET_FOOD_BY_ID_REQUEST = "GET_FOOD_BY_ID_REQUEST";
export const GET_FOOD_BY_ID_SUCCESS = "GET_FOOD_BY_ID_SUCCESS";
export const GET_FOOD_BY_ID_FAILURE = "GET_FOOD_BY_ID_FAILURE";